# Magento development composer file
# Björn Rennfanz <bjoern.rennfanz@br-edv.net>
#
data:
    build: data
db:
    image: mysql:5
    environment:
        - MYSQL_ROOT_PASSWORD=magento
        - MYSQL_USER=magento
        - MYSQL_PASSWORD=magento
        - MYSQL_DATABASE=magento
    volumes_from:
        - data
php:
    build: php
    links:
        - db
    volumes_from:
        - data
web:
    build: nginx
    links:
        - php:php_fpm
    ports:
        - "80:80"
    volumes_from:
        - data